### ISSUE TITLE
Create flow diagram to describe how data flows

### ISSUE THREAD

**Issue by 3vivekb** [codeforsanjose/smelly-cat#26]
Do this in google drawing.  Push image to repo.

**Comment by jkanive** [comment]
[SmellyCat.pdf](https://github.com/codeforsanjose/smelly-cat/files/512454/SmellyCat.pdf)
@3vivekb Please check the data flow diagram and let me know if you want me to make any changes

**Comment by 3vivekb** [comment]
This looks pretty good.
